import { Poppins } from 'next/font/google';
import Navbar from './components/Navbar';
import './globals.css';
import { AuthContextProvider } from './context/AuthContext';

const poppins = Poppins({ subsets: ['latin'], display: 'swap', weight: ["500"], });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthContextProvider>
          <Navbar />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
